import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}

    >
      <head>
        {/* <script src="/api/show"></script> */}
      </head>
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        {children}

        <Script
          src="api/show"
          // strategy="lazyOnload"
          // strategy="beforeInteractive"
          strategy="afterInteractive"
        ></Script>
      </body>
    </html>
  );
}
